// frontend/src/App.svelte
<script lang="ts">
  import { Router, Route, Link } from "svelte-navigator";
  import MainLayout from "./layout/MainLayout.svelte";
  import DashboardScreen from "./screens/DashboardScreen/DashboardScreen.svelte";
  import HomeScreen from "./screens/HomeScreen/HomeScreen.svelte";
</script>

<Router>

  <MainLayout>
    <main class="w-full h-full  bg-green-200 min-h-screen">
      <Route path="/">
        <HomeScreen />
      </Route>
  
      <Route path="dashboard">
        <DashboardScreen />
      </Route>
    </main>

    
  </MainLayout>
 
</Router>

<style>
</style>

// frontend/src/App.tsx
import { MantineProvider, Text } from '@mantine/core';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import { MainLayout } from './layout/MainLayout';
import DashboardScreen from './screens/main/DashboardScreen/DashboardScreen';
import HomeScreen from './screens/main/HomeScreen/HomeScreen';

function App() {
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <RouterProvider router={router} />;
    </MantineProvider>
  );
}

export default App;

const router = createBrowserRouter([
  {
    path: '/',
    element: <MainLayout />,
    children: [
      {
        path: '',
        element: <DashboardScreen />,
      },
      {
        path: 'game',
        element: <HomeScreen />,
      },
    ],
  },
]);
